# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f75dacfa166def1a2022c152c7c9f19439f8c657764405b909018f93d4ae910888ccc4f52b9c7497129c8733608456122c2c1dd018e4f7ffae9dad5f83ba54d8

test:
  secret_key_base: 6a8659c138ce2283191bf029793963c2d4d4262d1eb106da4f5e7e87c659494e10f69656ead902d616773cda31dde5599a84560ef55d052e80f5a806f3c0d741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
